// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3uJ4pvIWgiIKJvhy31v2vWNp-3fleWqw',
    appId: '1:339406979879:web:36e4c3b62884da237c9f02',
    messagingSenderId: '339406979879',
    projectId: 'recall-cfeb3',
    authDomain: 'recall-cfeb3.firebaseapp.com',
    storageBucket: 'recall-cfeb3.firebasestorage.app',
    measurementId: 'G-08CP7DGQKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtROe9-fCtaYh2YXePWdpI3ZXB6hsYyXQ',
    appId: '1:339406979879:android:c4a4bed5cc0802b97c9f02',
    messagingSenderId: '339406979879',
    projectId: 'recall-cfeb3',
    storageBucket: 'recall-cfeb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuW3AH-zpoPxocWKQSBM1MWomKs53EhjU',
    appId: '1:339406979879:ios:b0e100e1d8ea85797c9f02',
    messagingSenderId: '339406979879',
    projectId: 'recall-cfeb3',
    storageBucket: 'recall-cfeb3.firebasestorage.app',
    iosBundleId: 'com.recall.app.recall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3uJ4pvIWgiIKJvhy31v2vWNp-3fleWqw',
    appId: '1:339406979879:web:6b3c0134e95c4cd47c9f02',
    messagingSenderId: '339406979879',
    projectId: 'recall-cfeb3',
    authDomain: 'recall-cfeb3.firebaseapp.com',
    storageBucket: 'recall-cfeb3.firebasestorage.app',
    measurementId: 'G-B78MJBWDK8',
  );
}
